spring:
  application:
    name: NuMeAppHex
  data:
    mongodb:
      uri: mongodb://localhost:27017/pruebas

server:
  port: 8082

logging:
  level:
    org.springframework.web: DEBUG
    com.ejercicios.primeraPractica: DEBUG
  file:
    path: logs
    name: spring-boot-application.log
